// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ConfigurationRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ConfigurationRequest getRootAsConfigurationRequest(ByteBuffer _bb) { return getRootAsConfigurationRequest(_bb, new ConfigurationRequest()); }
  public static ConfigurationRequest getRootAsConfigurationRequest(ByteBuffer _bb, ConfigurationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConfigurationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mode() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer modeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public bpio.ModeConfiguration modeConfiguration() { return modeConfiguration(new bpio.ModeConfiguration()); }
  public bpio.ModeConfiguration modeConfiguration(bpio.ModeConfiguration obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public boolean modeBitorderMsb() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean modeBitorderLsb() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean psuDisable() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean psuEnable() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long psuSetMv() { int o = __offset(16); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int psuSetMa() { int o = __offset(18); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 300; }
  public boolean pullupDisable() { int o = __offset(20); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean pullupEnable() { int o = __offset(22); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int ioDirectionMask() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int ioDirection() { int o = __offset(26); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int ioValueMask() { int o = __offset(28); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int ioValue() { int o = __offset(30); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean ledResume() { int o = __offset(32); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long ledColor(int j) { int o = __offset(34); return o != 0 ? (long)bb.getInt(__vector(o) + j * 4) & 0xFFFFFFFFL : 0; }
  public int ledColorLength() { int o = __offset(34); return o != 0 ? __vector_len(o) : 0; }
  public IntVector ledColorVector() { return ledColorVector(new IntVector()); }
  public IntVector ledColorVector(IntVector obj) { int o = __offset(34); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer ledColorAsByteBuffer() { return __vector_as_bytebuffer(34, 4); }
  public ByteBuffer ledColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 4); }
  public String printString() { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer printStringAsByteBuffer() { return __vector_as_bytebuffer(36, 1); }
  public ByteBuffer printStringInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 36, 1); }
  public boolean hardwareBootloader() { int o = __offset(38); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hardwareReset() { int o = __offset(40); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hardwareSelftest() { int o = __offset(42); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int pwmPin() { int o = __offset(44); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean pwmEnable() { int o = __offset(46); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean pwmDisable() { int o = __offset(48); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long pwmFrequencyHz() { int o = __offset(50); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int pwmDutyX10() { int o = __offset(52); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 500; }

  public static int createConfigurationRequest(FlatBufferBuilder builder,
      int modeOffset,
      int modeConfigurationOffset,
      boolean modeBitorderMsb,
      boolean modeBitorderLsb,
      boolean psuDisable,
      boolean psuEnable,
      long psuSetMv,
      int psuSetMa,
      boolean pullupDisable,
      boolean pullupEnable,
      int ioDirectionMask,
      int ioDirection,
      int ioValueMask,
      int ioValue,
      boolean ledResume,
      int ledColorOffset,
      int printStringOffset,
      boolean hardwareBootloader,
      boolean hardwareReset,
      boolean hardwareSelftest,
      int pwmPin,
      boolean pwmEnable,
      boolean pwmDisable,
      long pwmFrequencyHz,
      int pwmDutyX10) {
    builder.startTable(25);
    ConfigurationRequest.addPwmFrequencyHz(builder, pwmFrequencyHz);
    ConfigurationRequest.addPrintString(builder, printStringOffset);
    ConfigurationRequest.addLedColor(builder, ledColorOffset);
    ConfigurationRequest.addPsuSetMv(builder, psuSetMv);
    ConfigurationRequest.addModeConfiguration(builder, modeConfigurationOffset);
    ConfigurationRequest.addMode(builder, modeOffset);
    ConfigurationRequest.addPwmDutyX10(builder, pwmDutyX10);
    ConfigurationRequest.addPsuSetMa(builder, psuSetMa);
    ConfigurationRequest.addPwmDisable(builder, pwmDisable);
    ConfigurationRequest.addPwmEnable(builder, pwmEnable);
    ConfigurationRequest.addPwmPin(builder, pwmPin);
    ConfigurationRequest.addHardwareSelftest(builder, hardwareSelftest);
    ConfigurationRequest.addHardwareReset(builder, hardwareReset);
    ConfigurationRequest.addHardwareBootloader(builder, hardwareBootloader);
    ConfigurationRequest.addLedResume(builder, ledResume);
    ConfigurationRequest.addIoValue(builder, ioValue);
    ConfigurationRequest.addIoValueMask(builder, ioValueMask);
    ConfigurationRequest.addIoDirection(builder, ioDirection);
    ConfigurationRequest.addIoDirectionMask(builder, ioDirectionMask);
    ConfigurationRequest.addPullupEnable(builder, pullupEnable);
    ConfigurationRequest.addPullupDisable(builder, pullupDisable);
    ConfigurationRequest.addPsuEnable(builder, psuEnable);
    ConfigurationRequest.addPsuDisable(builder, psuDisable);
    ConfigurationRequest.addModeBitorderLsb(builder, modeBitorderLsb);
    ConfigurationRequest.addModeBitorderMsb(builder, modeBitorderMsb);
    return ConfigurationRequest.endConfigurationRequest(builder);
  }

  public static void startConfigurationRequest(FlatBufferBuilder builder) { builder.startTable(25); }
  public static void addMode(FlatBufferBuilder builder, int modeOffset) { builder.addOffset(0, modeOffset, 0); }
  public static void addModeConfiguration(FlatBufferBuilder builder, int modeConfigurationOffset) { builder.addOffset(1, modeConfigurationOffset, 0); }
  public static void addModeBitorderMsb(FlatBufferBuilder builder, boolean modeBitorderMsb) { builder.addBoolean(2, modeBitorderMsb, false); }
  public static void addModeBitorderLsb(FlatBufferBuilder builder, boolean modeBitorderLsb) { builder.addBoolean(3, modeBitorderLsb, false); }
  public static void addPsuDisable(FlatBufferBuilder builder, boolean psuDisable) { builder.addBoolean(4, psuDisable, false); }
  public static void addPsuEnable(FlatBufferBuilder builder, boolean psuEnable) { builder.addBoolean(5, psuEnable, false); }
  public static void addPsuSetMv(FlatBufferBuilder builder, long psuSetMv) { builder.addInt(6, (int) psuSetMv, (int) 0L); }
  public static void addPsuSetMa(FlatBufferBuilder builder, int psuSetMa) { builder.addShort(7, (short) psuSetMa, (short) 300); }
  public static void addPullupDisable(FlatBufferBuilder builder, boolean pullupDisable) { builder.addBoolean(8, pullupDisable, false); }
  public static void addPullupEnable(FlatBufferBuilder builder, boolean pullupEnable) { builder.addBoolean(9, pullupEnable, false); }
  public static void addIoDirectionMask(FlatBufferBuilder builder, int ioDirectionMask) { builder.addByte(10, (byte) ioDirectionMask, (byte) 0); }
  public static void addIoDirection(FlatBufferBuilder builder, int ioDirection) { builder.addByte(11, (byte) ioDirection, (byte) 0); }
  public static void addIoValueMask(FlatBufferBuilder builder, int ioValueMask) { builder.addByte(12, (byte) ioValueMask, (byte) 0); }
  public static void addIoValue(FlatBufferBuilder builder, int ioValue) { builder.addByte(13, (byte) ioValue, (byte) 0); }
  public static void addLedResume(FlatBufferBuilder builder, boolean ledResume) { builder.addBoolean(14, ledResume, false); }
  public static void addLedColor(FlatBufferBuilder builder, int ledColorOffset) { builder.addOffset(15, ledColorOffset, 0); }
  public static int createLedColorVector(FlatBufferBuilder builder, long[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt((int) data[i]); return builder.endVector(); }
  public static void startLedColorVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPrintString(FlatBufferBuilder builder, int printStringOffset) { builder.addOffset(16, printStringOffset, 0); }
  public static void addHardwareBootloader(FlatBufferBuilder builder, boolean hardwareBootloader) { builder.addBoolean(17, hardwareBootloader, false); }
  public static void addHardwareReset(FlatBufferBuilder builder, boolean hardwareReset) { builder.addBoolean(18, hardwareReset, false); }
  public static void addHardwareSelftest(FlatBufferBuilder builder, boolean hardwareSelftest) { builder.addBoolean(19, hardwareSelftest, false); }
  public static void addPwmPin(FlatBufferBuilder builder, int pwmPin) { builder.addByte(20, (byte) pwmPin, (byte) 0); }
  public static void addPwmEnable(FlatBufferBuilder builder, boolean pwmEnable) { builder.addBoolean(21, pwmEnable, false); }
  public static void addPwmDisable(FlatBufferBuilder builder, boolean pwmDisable) { builder.addBoolean(22, pwmDisable, false); }
  public static void addPwmFrequencyHz(FlatBufferBuilder builder, long pwmFrequencyHz) { builder.addInt(23, (int) pwmFrequencyHz, (int) 0L); }
  public static void addPwmDutyX10(FlatBufferBuilder builder, int pwmDutyX10) { builder.addShort(24, (short) pwmDutyX10, (short) 500); }
  public static int endConfigurationRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConfigurationRequest get(int j) { return get(new ConfigurationRequest(), j); }
    public ConfigurationRequest get(ConfigurationRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

