// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DataResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DataResponse getRootAsDataResponse(ByteBuffer _bb) { return getRootAsDataResponse(_bb, new DataResponse()); }
  public static DataResponse getRootAsDataResponse(ByteBuffer _bb, DataResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DataResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String error() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer errorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int dataRead(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataReadLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector dataReadVector() { return dataReadVector(new ByteVector()); }
  public ByteVector dataReadVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer dataReadAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer dataReadInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public boolean isAsync() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createDataResponse(FlatBufferBuilder builder,
      int errorOffset,
      int dataReadOffset,
      boolean isAsync) {
    builder.startTable(3);
    DataResponse.addDataRead(builder, dataReadOffset);
    DataResponse.addError(builder, errorOffset);
    DataResponse.addIsAsync(builder, isAsync);
    return DataResponse.endDataResponse(builder);
  }

  public static void startDataResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(0, errorOffset, 0); }
  public static void addDataRead(FlatBufferBuilder builder, int dataReadOffset) { builder.addOffset(1, dataReadOffset, 0); }
  public static int createDataReadVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createDataReadVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startDataReadVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addIsAsync(FlatBufferBuilder builder, boolean isAsync) { builder.addBoolean(2, isAsync, false); }
  public static int endDataResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DataResponse get(int j) { return get(new DataResponse(), j); }
    public DataResponse get(DataResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

