<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ConfigurationRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ConfigurationRequest
     */
    public static function getRootAsConfigurationRequest(ByteBuffer $bb)
    {
        $obj = new ConfigurationRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ConfigurationRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getMode()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getModeConfiguration()
    {
        $obj = new ModeConfiguration();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @return bool
     */
    public function getModeBitorderMsb()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getModeBitorderLsb()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getPsuDisable()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getPsuEnable()
    {
        $o = $this->__offset(14);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return uint
     */
    public function getPsuSetMv()
    {
        $o = $this->__offset(16);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return ushort
     */
    public function getPsuSetMa()
    {
        $o = $this->__offset(18);
        return $o != 0 ? $this->bb->getUshort($o + $this->bb_pos) : 300;
    }

    /**
     * @return bool
     */
    public function getPullupDisable()
    {
        $o = $this->__offset(20);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getPullupEnable()
    {
        $o = $this->__offset(22);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return byte
     */
    public function getIoDirectionMask()
    {
        $o = $this->__offset(24);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getIoDirection()
    {
        $o = $this->__offset(26);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getIoValueMask()
    {
        $o = $this->__offset(28);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getIoValue()
    {
        $o = $this->__offset(30);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return bool
     */
    public function getLedResume()
    {
        $o = $this->__offset(32);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @param int offset
     * @return uint
     */
    public function getLedColor($j)
    {
        $o = $this->__offset(34);
        return $o != 0 ? $this->bb->getUint($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getLedColorLength()
    {
        $o = $this->__offset(34);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    public function getPrintString()
    {
        $o = $this->__offset(36);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return bool
     */
    public function getHardwareBootloader()
    {
        $o = $this->__offset(38);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getHardwareReset()
    {
        $o = $this->__offset(40);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getHardwareSelftest()
    {
        $o = $this->__offset(42);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return byte
     */
    public function getPwmPin()
    {
        $o = $this->__offset(44);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return bool
     */
    public function getPwmEnable()
    {
        $o = $this->__offset(46);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getPwmDisable()
    {
        $o = $this->__offset(48);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return uint
     */
    public function getPwmFrequencyHz()
    {
        $o = $this->__offset(50);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return ushort
     */
    public function getPwmDutyX10()
    {
        $o = $this->__offset(52);
        return $o != 0 ? $this->bb->getUshort($o + $this->bb_pos) : 500;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startConfigurationRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(25);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ConfigurationRequest
     */
    public static function createConfigurationRequest(FlatBufferBuilder $builder, $mode, $mode_configuration, $mode_bitorder_msb, $mode_bitorder_lsb, $psu_disable, $psu_enable, $psu_set_mv, $psu_set_ma, $pullup_disable, $pullup_enable, $io_direction_mask, $io_direction, $io_value_mask, $io_value, $led_resume, $led_color, $print_string, $hardware_bootloader, $hardware_reset, $hardware_selftest, $pwm_pin, $pwm_enable, $pwm_disable, $pwm_frequency_hz, $pwm_duty_x10)
    {
        $builder->startObject(25);
        self::addMode($builder, $mode);
        self::addModeConfiguration($builder, $mode_configuration);
        self::addModeBitorderMsb($builder, $mode_bitorder_msb);
        self::addModeBitorderLsb($builder, $mode_bitorder_lsb);
        self::addPsuDisable($builder, $psu_disable);
        self::addPsuEnable($builder, $psu_enable);
        self::addPsuSetMv($builder, $psu_set_mv);
        self::addPsuSetMa($builder, $psu_set_ma);
        self::addPullupDisable($builder, $pullup_disable);
        self::addPullupEnable($builder, $pullup_enable);
        self::addIoDirectionMask($builder, $io_direction_mask);
        self::addIoDirection($builder, $io_direction);
        self::addIoValueMask($builder, $io_value_mask);
        self::addIoValue($builder, $io_value);
        self::addLedResume($builder, $led_resume);
        self::addLedColor($builder, $led_color);
        self::addPrintString($builder, $print_string);
        self::addHardwareBootloader($builder, $hardware_bootloader);
        self::addHardwareReset($builder, $hardware_reset);
        self::addHardwareSelftest($builder, $hardware_selftest);
        self::addPwmPin($builder, $pwm_pin);
        self::addPwmEnable($builder, $pwm_enable);
        self::addPwmDisable($builder, $pwm_disable);
        self::addPwmFrequencyHz($builder, $pwm_frequency_hz);
        self::addPwmDutyX10($builder, $pwm_duty_x10);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addMode(FlatBufferBuilder $builder, $mode)
    {
        $builder->addOffsetX(0, $mode, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addModeConfiguration(FlatBufferBuilder $builder, $modeConfiguration)
    {
        $builder->addOffsetX(1, $modeConfiguration, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addModeBitorderMsb(FlatBufferBuilder $builder, $modeBitorderMsb)
    {
        $builder->addBoolX(2, $modeBitorderMsb, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addModeBitorderLsb(FlatBufferBuilder $builder, $modeBitorderLsb)
    {
        $builder->addBoolX(3, $modeBitorderLsb, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPsuDisable(FlatBufferBuilder $builder, $psuDisable)
    {
        $builder->addBoolX(4, $psuDisable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPsuEnable(FlatBufferBuilder $builder, $psuEnable)
    {
        $builder->addBoolX(5, $psuEnable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPsuSetMv(FlatBufferBuilder $builder, $psuSetMv)
    {
        $builder->addUintX(6, $psuSetMv, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ushort
     * @return void
     */
    public static function addPsuSetMa(FlatBufferBuilder $builder, $psuSetMa)
    {
        $builder->addUshortX(7, $psuSetMa, 300);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPullupDisable(FlatBufferBuilder $builder, $pullupDisable)
    {
        $builder->addBoolX(8, $pullupDisable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPullupEnable(FlatBufferBuilder $builder, $pullupEnable)
    {
        $builder->addBoolX(9, $pullupEnable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoDirectionMask(FlatBufferBuilder $builder, $ioDirectionMask)
    {
        $builder->addByteX(10, $ioDirectionMask, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoDirection(FlatBufferBuilder $builder, $ioDirection)
    {
        $builder->addByteX(11, $ioDirection, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoValueMask(FlatBufferBuilder $builder, $ioValueMask)
    {
        $builder->addByteX(12, $ioValueMask, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoValue(FlatBufferBuilder $builder, $ioValue)
    {
        $builder->addByteX(13, $ioValue, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addLedResume(FlatBufferBuilder $builder, $ledResume)
    {
        $builder->addBoolX(14, $ledResume, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addLedColor(FlatBufferBuilder $builder, $ledColor)
    {
        $builder->addOffsetX(15, $ledColor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createLedColorVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putUint($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startLedColorVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addPrintString(FlatBufferBuilder $builder, $printString)
    {
        $builder->addOffsetX(16, $printString, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addHardwareBootloader(FlatBufferBuilder $builder, $hardwareBootloader)
    {
        $builder->addBoolX(17, $hardwareBootloader, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addHardwareReset(FlatBufferBuilder $builder, $hardwareReset)
    {
        $builder->addBoolX(18, $hardwareReset, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addHardwareSelftest(FlatBufferBuilder $builder, $hardwareSelftest)
    {
        $builder->addBoolX(19, $hardwareSelftest, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addPwmPin(FlatBufferBuilder $builder, $pwmPin)
    {
        $builder->addByteX(20, $pwmPin, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPwmEnable(FlatBufferBuilder $builder, $pwmEnable)
    {
        $builder->addBoolX(21, $pwmEnable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPwmDisable(FlatBufferBuilder $builder, $pwmDisable)
    {
        $builder->addBoolX(22, $pwmDisable, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPwmFrequencyHz(FlatBufferBuilder $builder, $pwmFrequencyHz)
    {
        $builder->addUintX(23, $pwmFrequencyHz, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ushort
     * @return void
     */
    public static function addPwmDutyX10(FlatBufferBuilder $builder, $pwmDutyX10)
    {
        $builder->addUshortX(24, $pwmDutyX10, 500);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endConfigurationRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
