//! Flatbuffer types for working with the BPIO2 binmode available on the Bus Pirate 5 and later.
//!
//! This crate consists entirely of the Rust code generated by `flatc`, and as such the meaning and
//! intended use of this library's types are not fully documented here.
//!
//! You should read the [BPIO2 documentation][docs], and pair the description of the tables there
//! with the API listing here. Examples of constructing the types are available in the crate's
//! [examples folder][examples].
//!
//! More general information on the use of flatbuffers can be found in the [flatbuffers
//! tutorial][fb-tut] (be sure to set the language of the examples to Rust) and the [flatbuffers
//! Rust language guide][fb-rust].
//!
//! [docs]: https://docs.buspirate.com/docs/binmode-reference/protocol-bpio2/
//! [examples]: https://github.com/DangerousPrototypes/BusPirate-BPIO2-flatbuffer-interface/tree/main/rust/bpio2/examples/
//! [fb-tut]: https://flatbuffers.dev/tutorial/
//! [fb-rust]: https://flatbuffers.dev/languages/rust/#using-the-flatbuffers-rust-library
#![no_std]

#[allow(unused_imports)]
#[allow(clippy::extra_unused_lifetimes)]
#[allow(clippy::missing_safety_doc)]
mod bpio_generated;

pub use bpio_generated::bpio::*;
