// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bpio
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DataResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DataResponse GetRootAsDataResponse(ByteBuffer _bb) { return GetRootAsDataResponse(_bb, new DataResponse()); }
  public static DataResponse GetRootAsDataResponse(ByteBuffer _bb, DataResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Error { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(4); }
  public byte DataRead(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataReadLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataReadBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDataReadBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDataReadArray() { return __p.__vector_as_array<byte>(6); }
  public bool IsAsync { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<bpio.DataResponse> CreateDataResponse(FlatBufferBuilder builder,
      StringOffset errorOffset = default(StringOffset),
      VectorOffset data_readOffset = default(VectorOffset),
      bool is_async = false) {
    builder.StartTable(3);
    DataResponse.AddDataRead(builder, data_readOffset);
    DataResponse.AddError(builder, errorOffset);
    DataResponse.AddIsAsync(builder, is_async);
    return DataResponse.EndDataResponse(builder);
  }

  public static void StartDataResponse(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(0, errorOffset.Value, 0); }
  public static void AddDataRead(FlatBufferBuilder builder, VectorOffset dataReadOffset) { builder.AddOffset(1, dataReadOffset.Value, 0); }
  public static VectorOffset CreateDataReadVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataReadVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataReadVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataReadVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataReadVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddIsAsync(FlatBufferBuilder builder, bool isAsync) { builder.AddBool(2, isAsync, false); }
  public static Offset<bpio.DataResponse> EndDataResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<bpio.DataResponse>(o);
  }
}


static public class DataResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Error*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*DataRead*/, 1 /*byte*/, false)
      && verifier.VerifyField(tablePos, 8 /*IsAsync*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
